[package]
name = "unnamed-sdl-project"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
specs = "0.18.0"
rand = "0.8.5"
rayon = "1.5.3"
